name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  statik:
    uses: csunibo/config/.github/workflows/deploy-statik.yml@main
    with:
      regex_include: "\\.(pdf|link|txt|c|java|sh)$"
