name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  REGEX_INCLUDE: "\\.(pdf|link|txt|c|java|sh)$"

jobs:
  statik:
    name: Generate and deploy static site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Restore go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install statik
        run: go install github.com/lucat1/statik@latest

      - name: Generate static directory listing
        run: $(go env GOPATH)/bin/statik -page .github/workflows/page.gohtml -l -b "https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/" -i "$REGEX_INCLUDE" site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    needs: statik
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
