name: Lint file names
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check file names
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./appunti
        if: always()
        with:
          path: "./appunti"
          pattern: '^(\.gitkeep|([a-z0-9]+(-[a-z0-9]+)*\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./dispense
        if: always()
        with:
          path: "./dispense"
          pattern: '^(\.gitkeep|(\d+(-[a-z0-9]+)+\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./esercizi
        if: always()
        with:
          path: "./esercizi"
          pattern: '^(\.gitkeep|([a-z0-9]+(-[a-z0-9]+)*\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./lavagne
        if: always()
        with:
          path: "./lavagne"
          pattern: '^(\.gitkeep|(\d{4}-\d{2}-\d{2}(-[a-z0-9]+)+\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./libri
        if: always()
        with:
          path: "./libri"
          pattern: '^(\.gitkeep|([a-z0-9]+(-[a-z0-9]+)*\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./lucidi
        if: always()
        with:
          path: "./lucidi"
          pattern: '^(\.gitkeep|(\d+(-[a-z0-9]+)+\.[a-zA-Z]+))$'
          recursive: "true"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./prove
        if: always()
        with:
          path: "./prove"
          pattern: '^(\.gitkeep)|((scritto|orale)-(\d{4}-\d{2}-\d{2}))$'
          recursive: "false"

      - uses: csunibo/lint-filenames@master
        name: Lint file names under ./varie
        if: always()
        with:
          path: "./varie"
          pattern: '^(\.gitkeep|([a-z0-9]+(-[a-z0-9]+)*\.[a-zA-Z]+))$'
          recursive: "true"
